### ISSUE TITLE
TypeError when running httpRESTPolling Tests

### ISSUE THREAD

**Issue by kevincrabbe** [nio-blocks/http_blocks#44] opened 2016-06-21 20:43 UTC
Error Details:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/niocore/core/service/launcher.py", line 92, in configure
    self._configure_service(self._context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/niocore/core/service/launcher.py", line 141, in _configure_service
    self._service.do_configure(service_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/service/base.py", line 163, in configure
    block_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/service/base.py", line 194, in _create_and_configure_block
    block.do_configure(block_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 60, in configure
    self.init_post_id(query)
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 87, in init_post_id
    headers = self._get_headers()
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 140, in _get_headers
    "Authorization": "bearer " + self.token,
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by dorzel** [comment] 2017-01-19 21:21
Couldn't reproduce in http blocks itself or in reddit block with the version of http blocks used there, but will create a PR to update the http blocks to latest anyways.

**Comment by dorzel** [comment] 2017-01-19 21:27
Seems this was fixed in the reddit block by nio-blocks/reddit#7

**Closed by dorzel** 2017-01-19 21:27 UTC
